### ISSUE TITLE
Installation hangs on Windows

### ISSUE THREAD

**Issue by LachlanStuart** [akornatskyy/wheezy.template#23]
Installing on Windows with a fresh Anaconda environment hangs pip:

```
(base) C:\Users\WIN10\dev>pip install wheezy.template
Collecting wheezy.template
  Using cached wheezy.template-3.0.1.tar.gz (18 kB)
```

Running pip with `-v` to show logs reveals the cause:

```
Collecting wheezy.template
  Created temporary directory: C:\Users\WIN10\AppData\Local\Temp\pip-unpack-lxmjzzko
  Getting credentials from keyring for files.pythonhosted.org
  Looking up "https://files.pythonhosted.org/packages/40/cc/e15116058981aa30d4f7b0852126c69ca92bdcdf86470e35afcab69fddd5/wheezy.template-3.0.1.tar.gz" in the cache
  Current age based on date: 753
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 753
  Using cached wheezy.template-3.0.1.tar.gz (18 kB)
  Added wheezy.template from https://files.pythonhosted.org/packages/40/cc/e15116058981aa30d4f7b0852126c69ca92bdcdf86470e35afcab69fddd5/wheezy.template-3.0.1.tar.gz#sha256=8158c6821f759a424a0e4428c62104e78c37bc53d91be149072862d2764fe1e0 to build tracker 'C:\\Users\\WIN10\\AppData\\Local\\Temp\\pip-req-tracker-v5soqxfs'
    Running setup.py (path:C:\Users\WIN10\AppData\Local\Temp\pip-install-0fskwf9o\wheezy-template\setup.py) egg_info for package wheezy.template
    Created temporary directory: C:\Users\WIN10\AppData\Local\Temp\pip-pip-egg-info-tvikoj9_
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
        exitcode = _main(fd, parent_sentinel)
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
        prepare(preparation_data)
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
        _fixup_main_from_path(data['init_main_from_path'])
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
        main_content = runpy.run_path(main_path,
      File "C:\Users\WIN10\anaconda3\lib\runpy.py", line 265, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "C:\Users\WIN10\anaconda3\lib\runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "C:\Users\WIN10\anaconda3\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\Users\WIN10\AppData\Local\Temp\pip-install-0fskwf9o\wheezy-template\setup.py", line 13, in <module>
        extra["ext_modules"] = cythonize(
      File "C:\Users\WIN10\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 1078, in cythonize
        pool = multiprocessing.Pool(
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\context.py", line 119, in Pool
        return Pool(processes, initializer, initargs, maxtasksperchild,
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\pool.py", line 212, in __init__
        self._repopulate_pool()
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
        return self._repopulate_pool_static(self._ctx, self.Process,
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
        w.start()
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\process.py", line 121, in start
        self._popen = self._Popen(self)
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
        return Popen(process_obj)
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
        prep_data = spawn.get_preparation_data(process_obj._name)
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
        _check_not_importing_main()
      File "C:\Users\WIN10\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
        raise RuntimeError('''
    RuntimeError:
            An attempt has been made to start a new process before the
            current process has finished its bootstrapping phase.

            This probably means that you are not using fork to start your
            child processes and you have forgotten to use the proper idiom
            in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce an executable.

(The above exception is repeated over and over)
```

This seems to be an old, unresolved [bug in Cython](https://github.com/cython/cython/issues/3262) that happens when `nthreads>1`.

Unfortunately I don't have a Windows dev environment set up to make a PR for this. I only found out about it due to a [bug report from a user](https://github.com/alexandrovteam/pyimzML/issues/20)

Would it possible to implement one of the workarounds from [the Cython bug report](https://github.com/cython/cython/issues/3262) - such as setting `nthreads=0` or wrapping the code block in `if __name__ == '__main__':`?

**Comment by akornatskyy** [comment]
Setting `nthreads=0` helps. Could you, please, collaborate a bit more about the second option: "wrapping the code block...".

**Comment by LachlanStuart** [comment]
There's a good explanation about the general `if __name__ == '__main__'` pattern [here](https://stackoverflow.com/a/419189/432578).

On Linux, multiprocessing starts new processes by forking the existing process, which usually doesn't cause problems because the forked processes start with all Python state copied from the existing process. However, on Windows, multiprocessing starts new processes by re-launching the current process. This re-runs all the code for the current application, which in this case causes more calls to `cythonize` and to multiprocessing - multiprocessing raises an error to prevent exponential duplication of processes, but `cythonize` sees the error and just retries. If you use  `if __name__ == '__main__'` pattern, `__name__` won't be `'__main__'` in the re-launched processes, so it can be used to skip the `cythonize` call that shouldn't re-run in the re-launched processes.

There's an example of how to do this in a `setup.py` file in [Cython's setup.py](https://github.com/cython/cython/blob/master/setup.py#L231-L299). For wheezy.templates, I think this would mean moving all code in setup.py (except for the imports) into a `run_build()` function, then adding this to the end of the file:
```python
if __name__ == '__main__':
    run_build()
```

**Comment by akornatskyy** [comment]
Version 3.0.2 should be there shortly. I have disabled `nthreads` option in case `multiprocessing` method is `spawn`.

**Comment by LachlanStuart** [comment]
Awesome! Thank you very much @akornatskyy !

**Comment by akornatskyy** [comment]
@LachlanStuart could you please double check that it works for you?

**Comment by akornatskyy** [comment]
Thanks, @LachlanStuart. In case you use html escape in your code, you might consider to use html escape boost from [wheezy.html](https://github.com/akornatskyy/wheezy.html) package. I have just updated it to use similar cython workaround. Example is [here](https://github.com/akornatskyy/wheezy.template/blob/master/demos/bigtable/bigtable.py#L4) and [here](https://github.com/akornatskyy/wheezy.template/blob/master/demos/bigtable/bigtable.py#L143).
