### ISSUE TITLE
Include tests in sdist uploads

### ISSUE THREAD

**Issue by eli-schwartz** [akornatskyy/wheezy.template#34]
Sometimes, people want to run the project unittests to verify project sanity. This is especially important in linux distro packaging, where we need to check that:
- the versions of (build / runtime) dependencies packaged in the distro are compatible with the project
- when performing mass rebuilds against new versions of python (3.9, 3.10), everything still works
- no exotic bugs were introduced by distribution-specific implementation details of the underlying tech stack

Including the testsuite in the PyPI sdist is therefore appreciated. Test suites are generally not very big, and will not be included in wheels anyway.

It's "customary" to keep tests in a directory in the project root named tests/ and include them all in MANIFEST.in, this makes it easy to ensure all tests are included, and would also likely let you drop the `usedevelop=true` in tox.ini? Running pytest on the checked out sources kept on failing to import wheezy.template.tests etc. -- until I discovered `pytest --import-mode=importlib`, which wasn't an intuitive out of the box experience.

**Comment by akornatskyy** [comment]
Progress is in PR #35. So far moved tests to the project root and updated manifest to include into sdist. It appears `usedevelop=true` need to stay because of `src` directory, I think.
