### ISSUE TITLE
Question: Using import/from to include a function that generates a variable from Code Extension

### ISSUE THREAD

**Issue by AndydeCleyre** [akornatskyy/wheezy.template#43]
Thanks for this great project! I use it as a CLI tool frequently.

I'm not sure if this is possible, but I'm pretty sure my title isn't clear. Here's an example of the kind of thing I'm trying to do; maybe you can tell me what's possible and what's wrong.

`svc.run.wz`:
```bash
@require(svc)
#!/bin/execlineb -P

fdmove -c 2 1  # Send stderr to stdout

# Establish cgroup:
@def get_cgdir():
@(
from hashlib import md5
parent = svc['folder'].get('cgroups', '/sys/fs/cgroup/svcs')
cgdir = f"{parent}/{md5(svc['folder']['log'].encode()).hexdigest()}"
)\
@end
@get_cgdir()

getpid -E PID
foreground { mkdir -p @cgdir }
...
```
`svc.finish.wz`:
```bash
@require(svc)
@from "svc.run.wz" import get_cgdir
#!/bin/execlineb -P

# Establish cgroup:
@get_cgdir()

foreground { redirfd -r 0 @cgdir/cgroup.procs forstdin -E -p -C PID kill $PID }
...
```

The Code Extension bit is fine on its own, but I'm not sure if it gets evaluated when plopped into a substitution "function." Trying to render that first one results in

```python
  File "templates/svc.run.wz", line 17, in render
    foreground { mkdir -p @cgdir }
NameError: name 'cgdir' is not defined
```

Thanks for any guidance!

**Comment by akornatskyy** [comment]
The idea is to use `@(...)` block to define `get_cgdir` as a python function:

`svc.run.wz`:
```python
@require(svc)
#!/bin/execlineb -P

fdmove -c 2 1  # Send stderr to stdout

# Establish cgroup:

@(
    from hashlib import md5 
    def get_cgdir(svc):
        parent = svc['folder'].get('cgroups', '/sys/fs/cgroup/svcs')
        return f"{parent}/{md5(svc['folder']['log'].encode()).hexdigest()}"
)

getpid -E PID
foreground { mkdir -p @get_cgdir(svc) }
...
```

`svc.finish.wz`:
```python
@require(svc)
@from "svc.run.wz" import get_cgdir
#!/bin/execlineb -P

# Establish cgroup:

foreground { redirfd -r 0 @get_cgdir(svc)/cgroup.procs forstdin -E -p -C PID kill $PID }
...
```

**Comment by AndydeCleyre** [comment]
Oh, beautiful, thank you!

**Comment by AndydeCleyre** [comment]
`svc.run.wz`:
```python
@require(svc)
@(
    from hashlib import md5
    def cgdir(svc):
        parent = svc['folder'].get('cgroups', '/sys/fs/cgroup/svcs')
        return f"{parent}/{md5(svc['folder']['log'].encode()).hexdigest()}"
)
```
`svc.finish.wz`:
```python
@require(svc)
@from "svc.run.wz" import cgdir
```
```console
$ wheezy.template svc.finish.wz '{"svc": {"folder": {"log": "/tmp"} } }' 
```
```python
Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/09cf31f32589c76e6833d3dd7df7ed21/venv/bin/wheezy.template", line 8, in <module>
    sys.exit(main())
  File "/home/andy/.local/share/venvs/09cf31f32589c76e6833d3dd7df7ed21/venv/lib/python3.9/site-packages/wheezy/template/console.py", line 44, in main
    sys.stdout.write(t.render(load_context(args.context)))
  File "/home/andy/.local/share/venvs/09cf31f32589c76e6833d3dd7df7ed21/venv/lib/python3.9/site-packages/wheezy/template/engine.py", line 28, in render
    return self.render_template(ctx, {}, {})
  File "svc.finish.wz", line 2, in render
    @from "svc.run.wz" import cgdir
KeyError: 'cgdir'
```
I'm still missing something, but can't spot it.

**Comment by akornatskyy** [comment]
It appears when I replied to you I actually run `svc.run.wz`, but not as an import from `svc.finish.wz`.

When module `svc.run.wz` is imported, builder explicitly ignores anything but `@def` template directives (see [here](https://github.com/akornatskyy/wheezy.template/blob/master/src/wheezy/template/ext/core.py#L141), other directives might have a side effect during import, probably it makes sense to warn about this?).

The solution is to define `cgdir` as a template function, use code block inside to define python function and call it. If spaces are important need to watch for indents and use line join.

`svc.run.wz`:
```python
@def cgdir(svc):
@(
from hashlib import md5
def f():
    parent = svc['folder'].get('cgroups', '/sys/fs/cgroup/svcs')
    return f"{parent}/{md5(svc['folder']['log'].encode()).hexdigest()}"
)\
@f()\
@end
```
`svc.finish.wz`:
```python
@require(svc)
@from "svc.run.wz" import cgdir

@# I use '|' to show that there are no extra spaces.
|@cgdir(svc)|
```

```sh
$ wheezy.template svc.finish.wz '{"svc": {"folder": {"log": "/tmp"} } }' 
|/sys/fs/cgroup/svcs/d42b9c57d24cf5db3bd8d332dc35437f|
```

**Comment by akornatskyy** [comment]
Alternative solution is to define `utils.py` python module and import it:

`utils.py`:
```python
from hashlib import md5

def cgdir(svc):
    parent = svc['folder'].get('cgroups', '/sys/fs/cgroup/svcs')
    return f"{parent}/{md5(svc['folder']['log'].encode()).hexdigest()}"
```

`svc.finish.wz`:
```python
@require(svc)
@(
  import sys
  sys.path.append('.')
  utils = __import__('utils')
)

@utils.cgdir(svc)
```

```sh
$ wheezy.template svc.finish.wz '{"svc": {"folder": {"log": "/tmp"} } }' 
|/sys/fs/cgroup/svcs/d42b9c57d24cf5db3bd8d332dc35437f|
```

**Comment by akornatskyy** [comment]
A slightly different alternative with use of `PYTHONPATH` environment variable:


```python
@require(svc)
@(from utils import cgdir)

@cgdir(svc)
```
Here '.' path is an actual location of `utils` python module:
```sh
$ PYTHONPATH=.  wheezy.template svc.finish.wz '{"svc": {"folder": {"log": "/tmp"} } }'
```

**Comment by AndydeCleyre** [comment]
Thank you very much. My favorite option here is the separate py file, with the python path env variable, and it's working great.

Can you elaborate just a bit on why the original attempt from this issue (not using a python function) is incorrect?

**Comment by akornatskyy** [comment]
when you say "original attempt", do you mean the attempt you initially posted on the very top of this discussion?

**Comment by AndydeCleyre** [comment]
Yes, that's what I mean. Thanks!

**Comment by akornatskyy** [comment]
`cgdir` is a variable defined within `get_cgdir` function scope, thus as the error suggests it not defined outside (in global scope). So to use it outside you need to define it outside of function scope (globally) instead (not really a good idea).
